/*
 * This source file was generated by the Gradle 'init' task
 */
package com.freetime.app;

import okhttp3.OkHttpClient;
import okhttp3.Request;
import okhttp3.Response;
import java.io.FileOutputStream;
import java.io.InputStream;
import java.io.File;

public class Launcher {
    public static void main(String[] args) throws Exception {
        String url = "https://api.modrinth.com/v2/project/EDFggNY3/download";
        File output = new File("modpack.mrpack");

        OkHttpClient client = new OkHttpClient();
        Request request = new Request.Builder()
                .url(url)
                .build();

        try (Response response = client.newCall(request).execute()) {
            InputStream is = response.body().byteStream();
            FileOutputStream fos = new FileOutputStream(output);
            byte[] buffer = new byte[8192];
            int length;
            while ((length = is.read(buffer)) > 0) {
                fos.write(buffer, 0, length);
            }
            fos.close();
            System.out.println("Downloaded modpack.mrpack!");
        }
    }
}
